name: allocate

services:
  api:
    build: ./backend
    expose:
      - "5000"
    environment:
      - ALLOCATE_DATABASE=${DOCKER_ALLOCATE_DATABASE}
      - ALLOCATE_JWT_SECRET_KEY=${DOCKER_ALLOCATE_JWT_SECRET_KEY}
      - ALLOCATE_JWT_REFRESH_KEY=${DOCKER_ALLOCATE_JWT_REFRESH_KEY}
      - LANGFUSE_PUBLIC_KEY=${DOCKER_LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${DOCKER_LANGFUSE_SECRET_KEY}
      - LANGFUSE_HOST=${DOCKER_LANGFUSE_HOST}
      - LANGFUSE_TRACING_ENVIRONMENT=${DOCKER_LANGFUSE_TRACING_ENVIRONMENT}
      - ALLOCATE_OPENROUTER_API_KEY=${DOCKER_ALLOCATE_OPENROUTER_API_KEY}
      - ALLOCATE_GROQ_API_KEY=${DOCKER_ALLOCATE_GROQ_API_KEY}
      - ALLOCATE_PLUNK_API_KEY=${DOCKER_ALLOCATE_PLUNK_API_KEY}
      - ALLOCATE_LINEAR_CLIENT_ID=${DOCKER_ALLOCATE_LINEAR_CLIENT_ID}
      - ALLOCATE_LINEAR_CLIENT_SECRET=${DOCKER_ALLOCATE_LINEAR_CLIENT_SECRET}
      - ALLOCATE_LINEAR_REDIRECT_URI=${DOCKER_ALLOCATE_LINEAR_REDIRECT_URI}
      - ALLOCATE_LINEAR_OAUTH_TOKEN_URL=${DOCKER_ALLOCATE_LINEAR_OAUTH_TOKEN_URL}
      - ALLOCATE_LINEAR_AUTH_URL=${DOCKER_ALLOCATE_LINEAR_AUTH_URL}
      - ALLOCATE_NOTION_CLIENT_ID=${DOCKER_ALLOCATE_NOTION_CLIENT_ID}
      - ALLOCATE_NOTION_REDIRECT_URI=${DOCKER_ALLOCATE_NOTION_REDIRECT_URI}
      - ALLOCATE_NOTION_AUTH_URL=${DOCKER_ALLOCATE_NOTION_AUTH_URL}
      - ALLOCATE_NOTION_SECRET=${DOCKER_ALLOCATE_NOTION_SECRET}
      - ALLOCATE_ENV=${DOCKER_ALLOCATE_ENV}
      - UVICORN_HOST=0.0.0.0
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_DB=${DOCKER_DATABASE_DB}
      - POSTGRES_USER=${DOCKER_DATABASE_USER}
      - POSTGRES_PASSWORD=${DOCKER_DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  caddy:
    image: caddy:2.10.2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - api

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
