"""add rrule and exdate to events

Revision ID: 71a6360c0a2a
Revises:
Create Date: 2025-07-16 06:36:06.562104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71a6360c0a2a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("rrule", sa.String(length=512), nullable=True))
    op.add_column("events", sa.Column("exdate", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "exdate")
    op.drop_column("events", "rrule")
    # ### end Alembic commands ###
