name: Python Ruff Lint

on: [push]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12.1"

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('backend/uv.lock') }}

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Install dependencies
        working-directory: backend
        run: uv sync --dev --frozen

      - name: Ruff format check
        working-directory: backend
        run: uv run ruff format --check .

      - name: Ruff lint
        working-directory: backend
        run: uv run ruff check .
